/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.9.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as adventureLogs from "../adventureLogs.js";
import type * as http from "../http.js";
import type * as lib_authorization from "../lib/authorization.js";
import type * as lib_stripe from "../lib/stripe.js";
import type * as lib_transactional from "../lib/transactional.js";
import type * as me from "../me.js";
import type * as userActions from "../userActions.js";
import type * as users from "../users.js";
import type * as waitlist from "../waitlist.js";
import type * as webhooks from "../webhooks.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  adventureLogs: typeof adventureLogs;
  http: typeof http;
  "lib/authorization": typeof lib_authorization;
  "lib/stripe": typeof lib_stripe;
  "lib/transactional": typeof lib_transactional;
  me: typeof me;
  userActions: typeof userActions;
  users: typeof users;
  waitlist: typeof waitlist;
  webhooks: typeof webhooks;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
